packages:
  # specify a package in a direct subdir of the root
  - "apps/*"
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in direct subdirs of packages/configs
  - "packages/configs/*"
  # all packages in direct subdirs of packages/core
  - "packages/core/*"
